/**
 * fetch-newsletter-threads.ts (#2452)
 *
 * Fetches newsletter threads from Gmail REST API and writes a compact
 * CapturedThread[] JSON — consuming only text/plain bodies (with HTML
 * stripped/truncated) so the orchestrator never loads full HTML emails
 * into its context window.
 *
 * Token-reduction rationale: the 0b-bis step in orchestrator-stage-0
 * previously called `mcp__claude_ai_Gmail__get_thread (FULL_CONTENT)` up to
 * ~20 times inline, loading 80–112k chars of HTML per newsletter email
 * directly into the parent context. This script offloads that I/O to a Bash
 * call — the orchestrator receives only a compact JSON summary.
 *
 * Usage:
 *   npx tsx scripts/fetch-newsletter-threads.ts \
 *     --senders "email1@example.com,email2@example.com" \
 *     --since-hours 48 \
 *     --out data/editions/{AAMMDD}/_internal/captured-newsletters.json
 *
 * Options:
 *   --senders    Comma-separated list of sender email addresses to search for.
 *   --since-hours  How far back to search (default: 48).
 *   --body-limit   Max chars to keep from each body (default: 8000).
 *   --out          Output file path.
 *   --dry-run      Print thread count and first thread summary, no file write.
 *
 * Output file: CapturedThread[] (same shape as capture-newsletter-urls.ts expects)
 * Stdout: JSON summary { threads_found, threads_written, skipped_no_body }
 *
 * Requires data/.credentials.json (generated by scripts/oauth-setup.ts).
 */

import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gFetch } from "./google-auth.ts";
import type { GmailMessagePart } from "./lib/schemas/gmail.ts";

const GMAIL_API = "https://www.googleapis.com/gmail/v1/users/me";

/** Maximum characters of body text kept per thread (token-reduction guard). */
export const DEFAULT_BODY_LIMIT = 8000;

// ---------------------------------------------------------------------------
// Types (re-used from capture-newsletter-urls.ts interface)
// ---------------------------------------------------------------------------

export interface CapturedThread {
  thread_id: string;
  sender: string;
  subject: string;
  date: string; // ISO date string
  body: string; // plain text, truncated to BODY_LIMIT
}

export interface FetchSummary {
  threads_found: number;
  threads_written: number;
  skipped_no_body: number;
}

// ---------------------------------------------------------------------------
// Gmail REST helpers
// ---------------------------------------------------------------------------

async function gmailRequest<T>(path: string): Promise<T> {
  const res = await gFetch(`${GMAIL_API}/${path}`);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Gmail API error (${res.status}) at /${path}: ${body.slice(0, 200)}`);
  }
  return res.json() as Promise<T>;
}

interface GmailThreadListResponse {
  threads?: Array<{ id: string; snippet?: string }>;
  resultSizeEstimate?: number;
}

/**
 * Search Gmail threads matching a query. Returns up to `maxResults` thread IDs.
 */
export async function searchThreadIds(
  query: string,
  maxResults = 20,
): Promise<string[]> {
  const params = new URLSearchParams({ q: query, maxResults: String(maxResults) });
  const data = await gmailRequest<GmailThreadListResponse>(`threads?${params}`);
  return (data.threads ?? []).map((t) => t.id);
}

// ---------------------------------------------------------------------------
// Body extraction — text/plain preferred, HTML stripped as fallback
// ---------------------------------------------------------------------------

function decodeBase64Url(str: string): string {
  const b64 = str.replace(/-/g, "+").replace(/_/g, "/");
  return Buffer.from(b64, "base64").toString("utf8");
}

/**
 * Recursively walk MIME parts, preferring text/plain. Returns empty string if
 * no readable body found.
 */
export function extractTextPart(part: GmailMessagePart): string {
  if (part.mimeType === "text/plain" && part.body?.data) {
    return decodeBase64Url(part.body.data);
  }
  if (part.parts) {
    for (const child of part.parts) {
      const text = extractTextPart(child);
      if (text) return text;
    }
  }
  return "";
}

/**
 * Minimal HTML stripper — extracts href URLs and visible text so URL
 * extraction still works when text/plain is absent.
 *
 * Intentionally lightweight: no external deps. Mirrors the stripHtml in
 * capture-newsletter-urls.ts but is kept local so this script is self-contained.
 */
export function stripHtmlForBody(html: string): string {
  // Preserve href values so URL extraction captures links
  let text = html.replace(/<a\s[^>]*href=["']([^"']+)["'][^>]*>/gi, "$1 ");
  text = text.replace(/<\/(p|div|tr|li)>/gi, "\n");
  text = text.replace(/<br\s*\/?>/gi, "\n");
  text = text.replace(/<[^>]+>/g, " ");
  text = text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
  text = text.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n");
  return text.trim();
}

/**
 * Fallback: extract HTML part when no text/plain found, strip tags.
 */
function extractHtmlPart(part: GmailMessagePart): string {
  if (part.mimeType === "text/html" && part.body?.data) {
    return stripHtmlForBody(decodeBase64Url(part.body.data));
  }
  if (part.parts) {
    for (const child of part.parts) {
      const text = extractHtmlPart(child);
      if (text) return text;
    }
  }
  return "";
}

function getHeader(
  headers: Array<{ name: string; value: string }>,
  name: string,
): string {
  return (
    headers.find((h) => h.name.toLowerCase() === name.toLowerCase())?.value ?? ""
  );
}

// ---------------------------------------------------------------------------
// Fetch single thread and convert to CapturedThread
// ---------------------------------------------------------------------------

interface GmailThreadFull {
  id: string;
  messages: Array<{
    id: string;
    internalDate: string;
    payload: {
      mimeType: string;
      headers: Array<{ name: string; value: string }>;
      body?: { data?: string };
      parts?: GmailMessagePart[];
    };
  }>;
}

/**
 * Fetch a single thread from Gmail REST API with full MIME structure,
 * extract text/plain body (or stripped HTML fallback), and return a compact
 * CapturedThread. Truncates body to `bodyLimit` chars.
 *
 * Why `format=full` (not `format=metadata`): we need the body to extract URLs.
 * But we truncate the extracted text immediately — the raw HTML never leaves
 * this function.
 */
export async function fetchThread(
  threadId: string,
  bodyLimit: number = DEFAULT_BODY_LIMIT,
): Promise<CapturedThread | null> {
  const thread = await gmailRequest<GmailThreadFull>(
    `threads/${threadId}?format=full`,
  );

  // Use the most recent message in the thread
  const messages = thread.messages ?? [];
  if (messages.length === 0) return null;

  // Sort by internalDate descending, pick latest
  const sorted = [...messages].sort(
    (a, b) => Number(b.internalDate) - Number(a.internalDate),
  );
  const msg = sorted[0];

  const headers = msg.payload.headers ?? [];
  const sender = getHeader(headers, "From");
  const subject = getHeader(headers, "Subject");
  const dateMs = Number(msg.internalDate);
  const date = isNaN(dateMs) ? new Date().toISOString() : new Date(dateMs).toISOString();

  // Extract body: text/plain first, stripped HTML as fallback
  let body = extractTextPart(msg.payload as GmailMessagePart);
  if (!body) {
    body = extractHtmlPart(msg.payload as GmailMessagePart);
  }

  // Truncate to limit — token-reduction core
  const truncated = body.length > bodyLimit ? body.slice(0, bodyLimit) : body;

  if (!truncated.trim()) return null; // no usable content

  return {
    thread_id: thread.id,
    sender,
    subject,
    date,
    body: truncated,
  };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

interface CliArgs {
  senders: string[];
  sinceHours: number;
  bodyLimit: number;
  outPath: string;
  dryRun: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    senders: [],
    sinceHours: 48,
    bodyLimit: DEFAULT_BODY_LIMIT,
    outPath: "",
    dryRun: false,
  };

  for (let i = 2; i < argv.length; i++) {
    switch (argv[i]) {
      case "--senders":
        args.senders = (argv[++i] ?? "")
          .split(",")
          .map((s) => s.trim())
          .filter(Boolean);
        break;
      case "--since-hours":
        args.sinceHours = parseInt(argv[++i] ?? "48", 10);
        break;
      case "--body-limit":
        args.bodyLimit = parseInt(argv[++i] ?? String(DEFAULT_BODY_LIMIT), 10);
        break;
      case "--out":
        args.outPath = argv[++i] ?? "";
        break;
      case "--dry-run":
        args.dryRun = true;
        break;
    }
  }

  return args;
}

async function main(argv: string[] = process.argv): Promise<void> {
  const args = parseArgs(argv);

  if (args.senders.length === 0) {
    console.error("--senders is required (comma-separated email addresses)");
    process.exit(1);
  }
  if (!args.outPath && !args.dryRun) {
    console.error("--out is required (unless --dry-run)");
    process.exit(1);
  }

  // Build Gmail search query: "from:(sender1 OR sender2) newer_than:Nd"
  const senderClause =
    args.senders.length === 1
      ? `from:${args.senders[0]}`
      : `from:(${args.senders.join(" OR ")})`;

  // Gmail accepts newer_than:Nd (days) — convert hours to days, ceiling
  const days = Math.ceil(args.sinceHours / 24);
  const query = `${senderClause} newer_than:${days}d`;

  const threadIds = await searchThreadIds(query, 20);

  if (threadIds.length === 0) {
    const summary: FetchSummary = { threads_found: 0, threads_written: 0, skipped_no_body: 0 };
    if (!args.dryRun && args.outPath) {
      const absOut = resolve(process.cwd(), args.outPath);
      mkdirSync(dirname(absOut), { recursive: true });
      const tmp = absOut + ".tmp";
      writeFileSync(tmp, JSON.stringify([], null, 2) + "\n", "utf8");
      renameSync(tmp, absOut);
    }
    console.log(JSON.stringify(summary, null, 2));
    return;
  }

  // Fetch threads sequentially (no parallelism needed — max 20 threads, each
  // is small once we discard HTML; parallelism adds complexity for little gain)
  const captured: CapturedThread[] = [];
  let skippedNoBody = 0;

  for (const id of threadIds) {
    try {
      const thread = await fetchThread(id, args.bodyLimit);
      if (thread) {
        captured.push(thread);
      } else {
        skippedNoBody++;
      }
    } catch (err) {
      // Non-fatal: log and continue
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[fetch-newsletter-threads] WARN thread ${id}: ${msg.slice(0, 200)}`);
      skippedNoBody++;
    }
  }

  const summary: FetchSummary = {
    threads_found: threadIds.length,
    threads_written: captured.length,
    skipped_no_body: skippedNoBody,
  };

  if (args.dryRun) {
    console.log("[dry-run] Would write:");
    if (captured.length > 0) {
      const first = captured[0];
      console.log(`  thread_id: ${first.thread_id}`);
      console.log(`  sender: ${first.sender}`);
      console.log(`  subject: ${first.subject}`);
      console.log(`  body (first 200 chars): ${first.body.slice(0, 200)}`);
    }
    console.log(JSON.stringify(summary, null, 2));
    return;
  }

  const absOut = resolve(process.cwd(), args.outPath);
  mkdirSync(dirname(absOut), { recursive: true });
  const tmp = absOut + ".tmp";
  writeFileSync(tmp, JSON.stringify(captured, null, 2) + "\n", "utf8");
  renameSync(tmp, absOut);

  console.log(JSON.stringify(summary, null, 2));
}

// ---------------------------------------------------------------------------
// Entry point guard (prevents main() from running when imported by tests)
// ---------------------------------------------------------------------------

const isMain =
  typeof process !== "undefined" &&
  process.argv[1] &&
  process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  main().catch((err) => {
    console.error("[fetch-newsletter-threads] Fatal:", err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
